version: 2.1

executors:
  maven-executor:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo

jobs:
  build:
    executor: maven-executor
    steps:
      - checkout
      
      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline
          
      - run:
          name: Run Tests
          command: mvn clean install

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
